name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
        - run: echo "Value of MY_SECRET: $MY_SECRET"

      - name: List files
        run: ls -la
