name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - run: ls -la
      
      - uses: kams-mash/gh-secrets-scanner-action@master
      
      - run: pwd

      - run: ls -la

      - run: cat git-secrets
