name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Check .env file already exists
        run: ls -la .

      - name: Show secret
        run: |
          echo $ENV_VARS
        env:
          ENV_VARS: ${{secrets.ENV_VARS}}

      - name: Create env file
        run: |
          touch .env
          echo "$ENV_VARS" >> .env
        env:
          ENV_VARS: ${{secrets.ENV_VARS}}

      - name: Set env as secret
        env:
          MY_VAL: ${{ secrets.ENV_VARS }}
        run: |
          import os
          data = open("file", "w")
          for q in (os.getenv("MY_VAL")):
            print q
            data.write(q)
        shell: python