name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Check .env file already exists
        run: ls -la .

      - name: Show secret
        run: |
          echo "${{ secrets.ENV_VARS }}"

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENV_VARS }}" >> .env

      - name: Check created env content
        run: cat .env