name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3

      # - uses: shine1594/secrets-to-env-action@master
      #   with:
      #     secrets: ${{ toJSON(secrets) }}
      #     secrets_env: production
      #     file_name_prod: .env

      # - uses: oNaiPs/secrets-to-env-action@v1
      #   with:
      #     secrets: ${{ toJSON(secrets) }}

      # - name: Create .env
      #   uses: weyheyhey/create-dotenv-action@v1
      #   with:
      #     wildecard: "VAR_"
      #     filename: ".env"

      - run: ls -la

      - run: cat .env
