name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Check .env file already exists
        run: ls -la .

      - name: Show secret
        run: |
          echo $ENV_VARS
        env:
          ENV_VARS: ${{secrets.ENV_VARS}}

      - name: Create env file
        run: |
          touch .env
          'echo "$ENV_VARS" > .env'
        env:
          ENV_VARS: ${{secrets.ENV_VARS}}

      - name: Check created env content
        run: cat .env