name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Show envs
        run: echo ${{secrets}}
