name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Run action
        uses: CezaryTarnowski-TomTom/gha-inject-secrets-into-file@v1
        with:
          secrets: ${{ toJson(secrets) }}
      - run: |
          echo .env
