name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Create env
        uses: du5rte/create-secrets-file@v1
        with: |
          file: .env
          path: .

      - name: List files
        run: ls -la
        

      - name: Read .env file
        run: cat .env

