name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment: TEST
    
    steps:
      
      - uses: actions/checkout@v3

      - uses: du5rte/create-secrets-file@v1
        with:
          secrets: |
            SECRET_1=${{ secrets.SECRET_1 }}
            SECRET_2=${{ secrets.SECRET_2 }}
            SECRET_3=${{ secrets.SECRET_3 }}
            SECRET_4=${{ secrets.SECRET_4 }}
            SECRET_5=${{ secrets.SECRET_5 }}

      # - uses: shine1594/secrets-to-env-action@master
      #   with:
      #     secrets: ${{ toJSON(secrets) }}
      #     secrets_env: production
      #     file_name_prod: .env
      
      - run: ls -la

      - run: cat .env
